apiVersion: v1
kind: PersistentVolume
metadata:
  name: changedetection-io-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/changedetection/data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - w32
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-io-data-pvc
  namespace: changedetection-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: changedetection-io-data-pv
  storageClassName: ""
