apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-io-data-pvc
  namespace: changedetection-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Leave storageClassName unset to use the cluster default StorageClass
  # storageClassName: "standard"
